# This is a basic workflow to help you get started with Actions
name: PanditBOT

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the main branch
  #push:
  #  branches: [ main ]
  schedule:
    # every 2 hours from 6am IST to 6pm IST
    - cron: "0 0 1 * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Setup Python
        uses: actions/setup-python@v4
        #with:
        #python-version: 3.10 #install the python needed
      - name: Library installation
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Updating JSON
        run: python repo.py
      - name: Git push
        run: |
          git config user.name PtPrashantTripathi
          git config user.email ptprashanttripathi@outlook.com
          git add repos.json
          git commit -m "[PanditBot] Updating Repos Data $(date +%Y-%m-%d_%H-%M-%S)"
          git push --quiet
